version: '3'

networks:
    database:
    testing:

services:
    redis:
        image: redis:latest
        container_name: scooter_redis
        restart: unless-stopped
        tty: true
        networks:
            - database

    server-node:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: server-node
        tty: true
        volumes:
            - .:/app
        networks:
            - database
            - testing

    testing-node:
        build:
            context: ./test
            dockerfile: Dockerfile
        tty: true
        container_name: testing-node
        volumes:
            - ./test:/app
        networks:
            - testing
